# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
facebook_key: &facebook_key
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>

development:
  <<: *facebook_key
  secret_key_base: b152abbc580b7f41230875396484f3f35b8792eef5df65cd6250cc4419bad64145c898c3e991aeb972b9223d136ad12690799a800b451cff3e3cfed1df062b19
  default_host: localhost

test:
  secret_key_base: 78d3f03a540b873b775229e0773236035bda6d9b416448dde8ebde5de51e4a43c2a4a3f36d2b27f6947b888d12a93d6774ab488a3779c20324638ada0023e1e9
  default_host: localhost
  facebook_key: FACEBOOK_KEY
  facebook_secret: FACEBOOK_SECRET

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *facebook_key
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  default_host: <%= ENV["DEFAULT_HOST"] || "edmalert.me" %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
